jellypbc/poster

- docker-compose.yaml
Note: had to increase the Docker memory limit on my host machine to 4GB or the GROBID service would keep crashing. 
Note note: When it crashes, it doesn't restart; maybe there is a way to do that?
> get grobid talking to webserver on docker image

- README.md
otherwise you get this
Gem::LoadError: You have already activated rake 12.3.0, but your Gemfile requires rake 13.0.1. Prepending `bundle exec` to your command may solve this.
> add bundle exec for docker setup command

- app/models/citation.rb
- app/models/post.rb
- app/serializers/post_serializer.rb
- app/services/diborg_service.rb
- app/services/grobid_service.rb
- app/views/uploads/show.html.slim
- db/migrate/20191210215019_change_string_columns_to_text_for_citations_and_posts.rb
- db/schema.rb
- spec/factories/posts.rb
- spec/models/post_spec.rb
- test/fixtures/posts.yml
- test/models/post_test.rb
Fixed an edge case where titles were long, this turns those columns into text columns instead of strings.
> Cleanup citations parsing

- .editorconfig
For sublime users, you'll have to install the editorconfig package.
> Adds editorconfig

- README.md
- config/database.yml
- docker-compose.yaml
- Run these services in Docker:
- grobid
- postgres
- redis
- Add docs (note: follow teardown instructions
in readme for existing docker setups so that
the postgres user gets set up properly)
- The services forward ports so they should
act the same as local versions from the Rails server's point of view
> dockerize dependencies

- LICENSE-APACHE
- LICENSE-MIT
- README.md
will discuss at our tuesday 12/17 meeting before it is ready for review
> Update license to MIT/Apache-2

- app/serializers/post_serializer.rb
- config/webpack/environment.js
For some reason, @rails/actioncable breaks when importing in production (see https://github.com/rails/rails/issues/35501, and https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md#excluding-node_modules-from-being-transpiled-by-babel-loader), this should fix it.
> Fixes actioncable

- app/controllers/posts_controller.rb
i made a change last week that shows all posts
when i am demoing, it is difficult for me to locate the post that was the upload
so changing it back to ```Post.primary```
> only show posts that are pdf uploads in index

- app/javascript/components/PostEditor.js
- app/javascript/components/PostViewer.js
- app/views/posts/show.html.slim
setting ```isProcessing``` to true based on the presence of the post body causes posts that are autogenerated reference posts and standalone posts created to display PostProcessPlaceholder (flubber animation) on infinite loop
this fix explicitly sets ```isProcessing``` state for posts with PDF upload
before: 
after:
> fixes infinite loop of PostProcessingPlaceholder on references and new posts

- app/assets/stylesheets/pages.scss
- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.slim
fixes https://github.com/jellypbc/poster/issues/144
the problem is root and /dashboard looks broken to the user. i commented out some css to make the visual UI look usable. i understand that @dennyluan is working on final scaffolding this week.
the reason this needs to be addressed before @dennyluan is finished with dashboard scaffolding is right now when users go to root or /dashboard while logged in is the page looks unfinished
before:
after:
> Fixes /dashboard visual UI

- app/views/pages/index.html.slim
This button leads to a ```mailto:aloha@jellypbc.com```.
The next iteration of this button is to link to a survey for potential users to fill out.
> Adds 'request early access' button to index

- app/controllers/posts_controller.rb
- app/javascript/components/Editor.js
- app/javascript/components/PostEditor.js
- app/javascript/components/editor-config/plugin-comment.js
This is kind of not ideal, but it fixes the comments losing their position by updating each comment on `updatePost()` from pulling from the DecorationSet in the editor's comment plugin.
Also fixes https://github.com/jellypbc/poster/issues/171
> Fixes comment deco position bug

- app/javascript/components/Floater.js
- app/javascript/components/PostEditor.js
- app/javascript/components/SearchBar.js
When navigating back to a page, the components that had placeholders were looking for elements that were removed and breaking the rest of the page.
Fixes https://github.com/jellypbc/poster/issues/167
> Fix placeholder removal for searchbar and posteditor

- app/controllers/comments_controller.rb
- app/javascript/components/Editor.js
- app/javascript/components/PostEditor.js
- app/javascript/components/editor-config/plugin-comment.js
- app/models/comment.rb
- app/serializers/comment_serializer.rb
- app/serializers/post_serializer.rb
- db/migrate/20200502020343_add_field_type_to_comments.rb
- db/migrate/20200502024810_add_index_to_comment_field_type.rb
- db/schema.rb
- spec/factories/comments.rb
- spec/models/comment_spec.rb
This PR breaks comments out into different `field_type`'s based on the editor (e.g. title editor, body editor), and integrates it into the Comment Plugin to support different types of comments.
Post-merge: Because this is a new column, all existing comments will no longer show up. For now, we'll migrate all existing comments to be body comments.
> Add field_type to comments and add commenting by editor field

- app/models/user.rb
fixes https://github.com/jellypbc/poster/issues/189 https://github.com/jellypbc/poster/issues/188
know issue:
- users can intentionally set username with a ```.``` which will return an error on /write /settings
> Fixes registration

- app/assets/stylesheets/pages.scss
- app/views/pages/index.html.slim
Added access to a login button on the homepage. This should make it easy for existing users to continue using Jelly as they can start navigation directly from the base URL. 
Previously, I used to keep a link to a random Jelly page bookmarked in order to enter the site. This should eliminate the need for doing something along those lines.
> added login button on index page 

- app/services/diborg_service.rb
fixes #134 
We tested this branch using this PDF and the app will not return duplicate text. https://arxiv.org/pdf/1703.01192.pdf
> Updates diborg to return a single copy of parsed text

- app/views/tags/index.html.slim
This modifies the tags table (poster.jellypbc.com/tags) to include the ID of the tag. Created by Cindy and I during a pair programming session. Go team! 
Before:
After:
> Added ID to tags table JEL-91

- app/models/user.rb
- app/views/tags/index.html.slim
- app/views/users/index.html.slim
Adds the ID of each user, their total number of comments, and the last time they commented to the users table. Done by Yash and Cindy during a pair programming session.
Table:
> Updates Users table JEL-90

- app/helpers/users_helper.rb
- app/models/user.rb
- app/views/users/index.html.slim
Fixes 500 error with /users that occurs when `user.comments` returns `nil`. ~~Updates user model to include the time since the user's last comment.~~
Moves logic from the view into users helper.
> Fixes 500 error on /users JEL-111

- app/javascript/components/PostEditor.js
Fixes a bug where if the title of a post is empty, the title of the page returns null. Replaces all cases of this occurrence with "Untitled".
Before:
After:
> Fixes "null" page title bug when title editor is empty JEL-114

- app/assets/stylesheets/core/_type.scss
- app/assets/stylesheets/core/variables.scss
> Updates inline code and code block styles

- app/javascript/components/Editor.js
- app/javascript/components/PostEditor.js
- app/javascript/components/editor-config/annotation-popup.js
- app/javascript/components/editor-config/comments.js
- app/javascript/components/editor-config/keys.js
- app/javascript/components/editor-config/menu.js
- app/javascript/components/editor-config/plugins.js
- app/javascript/components/editor-config/title-menu.js
Just some housekeeping. Rename comment plugin file, and removes editorview when editor component unmounts.
> Editor cleanup

- Contributing.md
- app/views/pages/about.html.slim
- app/views/pages/index.html.slim
fixes https://github.com/jellypbc/poster/issues/274
if you are an existing jelly slack member and logged in, clicking the invite URL will take you the slack workspace. 
if you are new, clicking the invite URL will take you to the slack registration flow.
> updates slack URLs to use invite URL

- app/javascript/components/ImageModal.js
- app/javascript/components/editor-config/images.js
- app/javascript/components/store.js
Rebased @alexkrolick's original PR (https://github.com/jellypbc/poster/pull/151).
This PR sets up a pattern that we can follow for using redux with prosemirror 'dispatching'. It uses redux toolkit's `createSlice` for a neat and orderly pattern.
> Img upload refactor 1

- app/javascript/components/editor-config/nodes.js
This PR removes the `header` node type and leaves the `heading` node type. 
Because the `header` node type is removed, new lines in the editor default to the `paragraph` node type instead of `header`. Because `ordered_list` and `bullet_list` node types [require the first child of a list item is a plain paragraph](https://prosemirror.net/docs/ref/#schema-list), having new lines in the editor default to `paragraph` allow markdown and menu buttons commands to create list nodes.
fixes one item in https://github.com/jellypbc/poster/issues/232
https://www.loom.com/share/2f58ee401192422bbd9e7a4b827ba51e?focus_title=1&muted=1
> Fixes ordered_list and bullet_list node types in editor

- app/assets/stylesheets/editor.scss
- app/assets/stylesheets/editor/placeholder.scss
- app/javascript/components/editor-config/placeholder.js
- app/javascript/components/editor-config/plugins.js
This PR includes placeholder style changes. 
https://www.loom.com/share/3bbbb03cf0dc4c669d2e71aa3528c32b
fixes https://github.com/jellypbc/poster/issues/283
refactor items:
polish items:
> Refactor and polish placeholder plugin

- app/assets/stylesheets/editor/sidebar.scss
this PR addresses https://github.com/jellypbc/poster/issues/262 but does not fully fix.
> Updates sidebar styles for lists and headings

- app/assets/stylesheets/editor/masthead.scss
- app/assets/stylesheets/editor/placeholder.scss
- app/assets/stylesheets/posts.scss
- app/javascript/components/Backlinks.js
- app/javascript/components/Citations.js
- app/javascript/components/PostEditor.js
- app/javascript/components/PostMasthead.js
- app/javascript/components/editor-config/marks.js
- app/views/posts/_placeholder_post.html.slim
This PR matches visual styles for the placeholder post with the post editor post. The placeholder post will not show a sidebar placeholder.
**after PR:**
placeholder
non-placeholder
**before PR:**
placeholder
non-placeholder
> Matches post editor styles with post placeholder styles

- app/assets/stylesheets/comments.scss
- app/javascript/components/CommentForm.js
- app/javascript/components/Floater.js
- app/javascript/components/editor-config/comments.js
addresses two bugs in [make editor gooder](https://github.com/jellypbc/poster/issues/318) https://github.com/jellypbc/poster/issues/318
menubar before:
menubar after:
threaded comment before:
threaded comment after:
> Hides menubar when no selection and updates threaded comment styles

- app/assets/stylesheets/editor/sidebar.scss
This PR decreases padding on blockquote styles in sidebar.
before:
after:
> Fix sidebar blockquote styles

- app/views/pages/index.html.slim
This PR adds `Log` to the homepage linking to our SoundCloud weekly audio updates.
> Adds Log to homepage

- app/controllers/citations_controller.rb
- app/controllers/posts_controller.rb
- app/javascript/components/Editor.js
- app/javascript/components/PostEditor.js
- app/javascript/components/editor-config/citations.js
- app/javascript/components/editor-config/images.js
- app/javascript/components/editor-config/keys.js
- config/routes.rb
This PR updates the `data_from` and `data_to` position of citations when a document changes, so the citations stay attached to theirl highlighted text.
Fixes https://github.com/jellypbc/poster/issues/233
Note: The title editor does not allow citations, so no citations are sent as data when saving the title editor.
after:
before:
> Preserves citation position to highlighted text

- app/controllers/tags_controller.rb
- app/views/shared/_footer.html.slim
- app/views/tags/show.html.slim
- app/views/users/show.html.slim
This PR fixes two bugs introduced in https://github.com/jellypbc/poster/pull/343.
1. citations tab on collection page showing no posts when posts exist
2. PostContainer tabs showing count of 10 posts when total posts > 10
after:
before:
> Fixes paginated_citations method and corrects post count in PostContainer tabs

- app/javascript/components/editor-config/icons.js
- app/javascript/components/editor-config/menu.js
- app/javascript/components/editor-config/nodes.js
- app/javascript/components/editor-config/plugins.js
- package.json
- yarn.lock
This PR removes footnotes plugin. The footnote UX provided by [@aeaton/prosemirror-footnotes](https://www.npmjs.com/package/@aeaton/prosemirror-footnotes) is not our desired footnote UX for Jelly.
For now, users can add footnotes by making text superscript and adding an inline comment. 
We may revisit footnotes in the future.
> Removes footnotes plugin

- .env.development
- .env.production.sample
- DEPLOYING.md
- Gemfile
- Gemfile.lock
- config.ru
Adds rack-canonical-host for root domain redirect. Also updates the documentation for this option.
> Set up canonical host redirect

- app/controllers/pages_controller.rb
- app/views/devise/shared/_links.html.slim
This PR sorts collections in alphabetical order and fixes invalid path used by devise. 
after:
before:
> Sorts collections by alphabetical order

- app/assets/stylesheets/editor/defaults.scss
- app/views/devise/shared/_links.html.slim
This PR adds padding below paragraph and heading nodes (ignores paragraph nodes in ul and ol and ignores empty paragraph nodes). Blockquote, code block, ul, ol use margin left of `2em`. 
User can copy from standard web page or external editors and paste content into Jelly resulting in expected copy paste behavior. Copy paste tested with Medium, Tumblr, Typora, The New York Times, PLOS.
Note: Copy and paste from Word and Google Docs is out of the scope of this PR. Copy and paste equations from PLOS to Jelly is also out of scope.
copy and paste demo:
after:
before:
> Fixes copy pasting into jelly from external sources and markdown editors

- app/assets/config/manifest.js
- app/controllers/tags_controller.rb
- app/javascript/components/TagForm.js
- config/routes.rb
This PR updates `TagForm` `handleDelete` to remove the selected tag from the post instead of destroying the tag. 
Fixes the following bug:
- removing a tag from post results in destroying the tag 😅
after:
Deleting a tag from a post removes tag from post.
before:
Deleting a tag from a post destroys the tag.
> Fixes removing tag from post in TagForm

- app/assets/stylesheets/editor/defaults.scss
- app/views/shared/_nav.html.slim
This PR updates the styles for the fallback of search in nav bar and post content in editor. Prior to this PR the fallback styles did not match the styles of react components producing a clunky user experience when loading the page. 
before:
left = fallback, right = react components rendered
after: 
left = fallback, right = react components rendered
> Matches nav bar and post page fallback styles to react component styles

- app/serializers/post_serializer.rb
This PR updates how title_comments are serialized, so that username shows in title comments.
after:
before:
> Fixes serialized comment data

- app/assets/stylesheets/editor/defaults.scss
- app/assets/stylesheets/editor/math.scss
- app/assets/stylesheets/editor/sidebar.scss
- app/javascript/components/editor-config/marks.js
This PR makes visual improvements to the sidebar minimap.
after:
before:
> Minimap visual improvements

- app/controllers/search_controller.rb
- app/javascript/components/PostsContainer.js
- app/javascript/components/SearchResultsContainer.js
- app/views/search/results.html.slim
- config/routes.rb
This PR improves search results page ux/ui design.
~fix bug where total number of results not matching number of posts shown~*
*Once this PR is approved and merged, check in production for the results pages returning < 10 results because some records no longer exist in the database. To fix, run `Post.reindex` in console to reindex and resolve. https://github.com/ankane/searchkick#to-reindex-or-not-to-reindex
after: 
before:
> Improves search results page design

- app/controllers/tags_controller.rb
- app/helpers/posts_helper.rb
- app/helpers/tags_helper.rb
- app/views/layouts/_head.html.slim
- app/views/posts/show.html.slim
- app/views/tags/show.html.slim
This PR adds `meta_title` and `meta_twitter_description` to generate twitter cards for collections.
Updates twitter cards for posts, so title defaults to `Untitled` and author to `Anonymous` when those fields are not present.
Twitter cards cannot be tested locally, so this will be tested live.
Addresses #353 
Collection twitter card design
Post twitter card design
> Adds twitter card for collections

- app/controllers/posts_controller.rb
Fixes #378. 
`tag` does not have a `post_id` attribute.
> Fixes 500 error on /edit pages

- app/views/posts/_placeholder_post.html.slim
With this PR, there is no visible difference between the placeholder post and the PostPage component.
The visible difference between placeholder post and PostPage component caused a jumpy experience for the user. This PR resolves that.
After:
(L = placeholder, R = PostPage component)
Before:
(L = placeholder, R = PostPage component)
> Match placeholder post styles to PostPage styles

- package.json
- yarn.lock
Fixes https://github.com/jellypbc/poster/issues/392
after:
before: 
reference: https://ursualexandr-21492.medium.com/uncaught-typeerror-cannot-convert-object-to-primitive-value-ea83623ca517
> Upgrades to jquery 3.5.1

- app/javascript/components/editor-config/comments.js
Fixes https://github.com/jellypbc/poster/issues/423
This PR fixes a bug introduced by https://github.com/jellypbc/poster/pull/417 where users are unable to reply to comments. This is a quick fix. For a full solution, we need to pass the accurate `highlightedText` from the CommentForm component into `handleReplySubmit` or generate the highlightedText string in `comments.js`.
I opted not to do a full fix because comments is not our priority right now. My estimate for a full fix is 1 hour to 1/2 day.
After:
Before:
> Fix reply to comment bug

- app/views/shared/_footer.html.slim
Bug: Footer was sitting on top of Log In/Registration button when user is zoomed in. Bug also happens on my tiny iPhone SE screen.
After:
Before:
> Fixes footer overlapping button
