jellypbc/poster

- app/assets/stylesheets/buttons.scss
- app/controllers/sessions_controller.rb
- app/helpers/sessions_helper.rb
- app/services/grobid_service.rb
- app/views/posts/index.html.slim
- app/views/uploads/index.html.slim
Fixes the grobid parser file_url fetching, it was not happy.
> Fix titles

- package.json
- yarn.lock
Dependency vulnerability update.
> Bump serialize-javascript

- .prettierrc
- app/assets/stylesheets/editor.scss
- app/javascript/components/HtmlEditor.js
- app/javascript/components/PostEditor.js
- app/serializers/post_serializer.rb
- package.json
- yarn.lock
- feature: debounce change handling
- feature: show save state in floating loading indicator
- add js tooling (eslint, prettier)
---
- view without whitespace diff: https://github.com/jellypbc/poster/pull/38/files?utf8=✓&diff=split&w=1
> Editor refactor

- app/assets/stylesheets/core/_layout.scss
- app/assets/stylesheets/posts.scss
- app/models/upload.rb
- app/views/layouts/application.html.slim
- app/views/posts/index.html.slim
- app/views/posts/show.html.slim
- app/views/uploads/index.html.slim
- app/views/uploads/show.html.slim
- app/views/users/index.html.erb
- app/views/users/show.html.erb
- config/environments/development.rb
After I upgraded my docker, I found that running just `docker-compose up figures grobid` services uses the wrong network hosts. This should fix it.
Eventually will add tests for this later 😬
> Fix post styles

- Gemfile
- Gemfile.lock
- Guardfile.rb
- README.md
- app/models/concerns/slug_history.rb
- app/services/diborg_service.rb
- bin/rspec
- config/initializers/bugsnag.rb
- spec/factories/citations.rb
- spec/models/citation_spec.rb
- spec/models/concerns/slug_history_spec.rb
- spec/models/post_spec.rb
- spec/models/upload_figure_spec.rb
- spec/models/upload_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
- spec/views/posts/show.html.erb_spec.rb
Chops off 10+ sec for loading specs using guard.
> Sets up guard to run on spring

- app/serializers/post_serializer.rb
> Force actioncable websocket connection to use wss

- app/views/devise/registrations/new.html.erb
- app/views/devise/shared/_registration_prompt.html.erb
- app/views/shared/_nav.html.slim
demo: https://www.loom.com/share/697f25f930dc4f8bbe4fede53ce0fc0f
> simplify user auth

- app/javascript/components/config/plugins.js
this PR may resolve errors with circleci pushing last two PRs to production 🤞🏽
these PRs got stuck 
https://github.com/jellypbc/poster/pull/81
https://github.com/jellypbc/poster/pull/77
https://circleci.com/gh/jellypbc/poster/182
https://circleci.com/gh/jellypbc/poster/176
> removes ./plugin-comment.css import

- app/javascript/components/Floater.js
- Fixes the floater menu position when scrolling in Y direction
> Small editor fixes

- app/assets/stylesheets/core/_navs.scss
- app/assets/stylesheets/pages.scss
- app/controllers/pages_controller.rb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_registration_prompt.html.erb
- app/views/layouts/application.html.slim
- app/views/pages/index.html.slim
- app/views/shared/_nav.html.slim
> updates nav bar

- .gitignore
- app/assets/stylesheets/posts.scss
- app/controllers/posts_controller.rb
- app/javascript/components/PostEditor.js
- app/javascript/components/PostMasthead.js
- app/models/concerns/slug_history.rb
- app/models/concerns/slugged.rb
- app/serializers/post_serializer.rb
- app/services/diborg_service.rb
- app/views/pages/index.html.slim
- app/views/posts/_placeholder_post.html.slim
known problems:
- title supports next line
- title supports marks and block types
- breaks url slug when title is blank
- breaks when the url slug is already taken (not unique)
> adds editor for post title

- app/mailers/user_mailer.rb
- app/views/user_mailer/welcome.text.erb
Trying to confirm our sendgrid.
> Set up test user mailer

- app/models/user.rb
- app/serializers/user_serializer.rb
- db/migrate/20200212030716_remove_password_digest_from_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
This column was breaking our devise config.
> Remove password_digest column from users

- app/views/posts/show.html.slim
Fixes https://github.com/jellypbc/poster/issues/108
> Fixes new uploads breaking due to title parsing

- Procfile.dev
- README.md
Updates the readme to use foreman in case you didn't already know to do so.
Just in one terminal session you can start everything needed using `foreman start -f Procfile.dev`.
> Adds foreman docs to readme

- app/assets/stylesheets/comments.scss
- app/assets/stylesheets/core/_buttons.scss
- app/assets/stylesheets/core/_variables.scss
- app/javascript/components/CommentForm.js
- app/javascript/components/config/plugin-comment.js
only weird thing is that `enter` keypresses get sent to the main editor (cancelling the reply and putting a newline in the text) so you can't submit with that
> inline reply for comments

- app/assets/stylesheets/pages.scss
- app/views/pages/pricing.html.slim
- app/views/pages/terms.html.slim
- config/routes.rb
> adds terms and conditions and privacy policy

- app/assets/stylesheets/core/_type.scss
- app/assets/stylesheets/core/_variables.scss
- app/assets/stylesheets/posts.scss
- app/views/layouts/_head.html.slim
- app/views/pages/dashboard.html.slim
- app/views/posts/_post_row.html.slim
This PR changes over our fonts to use the system fonts - e.g. whatever is found on Mac OS X, Windows, Android, etc, natively. This reduces our payload size.
https://css-tricks.com/snippets/css/system-font-stack/
> Changes fonts to use system font stack

- app/assets/stylesheets/core/_navs.scss
- app/javascript/components/Editor.js
- app/javascript/components/PostViewer.js
- app/views/posts/show.html.slim
- app/views/shared/_nav.html.slim
- app/views/styleguide/_type.html.slim
Adds read only mode for logged out users.
> Read only mode

- app/javascript/components/Floater.js
- app/javascript/components/PostViewer.js
- app/javascript/components/config/annotation-popup.js
- app/javascript/components/config/index.js
- app/views/admin/users/index.html.slim
> Adds different annotation menu for PostViewer

- app/javascript/components/config/plugin-comment.js
- app/javascript/components/config/plugins.js
- app/javascript/components/config/select.js
Fixes an issue where the floater menu stays active after clicking outside of the selection.
> Adds select plugin to editor

- Gemfile
- Gemfile.lock
- config/initializers/searchkick.rb
Adds a gem for searchkick persistent connections.
> Adds typhoeus gem for searchkick

- app/assets/stylesheets/pages.scss
- app/controllers/pages_controller.rb
- app/controllers/tags_controller.rb
- app/views/pages/jobs.html.slim
- config/routes.rb
> Adds an internship job page

- app/javascript/components/SearchBar.js
- package.json
- yarn.lock
clean up some console warnings.
> Bumps react-autosuggest

- app/assets/stylesheets/comments.scss
- app/assets/stylesheets/posts.scss
- app/javascript/components/CommentForm.js
- app/javascript/components/Editor.js
- app/javascript/components/editor-config/plugin-comment.js
- app/models/user.rb
- app/serializers/post_serializer.rb
- app/serializers/user_serializer.rb
- app/views/posts/show.html.slim
This PR adds the users to the comments and comment form. This works for both logged out and logged in users.
For now we're using a stubbed out user object serialized and passed in as props until we add in full guest users from devise.
> Adds users to comments

- app/javascript/components/Editor.js
- app/javascript/components/PostEditor.js
- app/javascript/components/editor-config/plugins.js
This PR does some clean up to rearrange and refactor the `PostEditor` component.
> Refactor editor

- app/assets/stylesheets/core/_type.scss
- app/assets/stylesheets/editor.scss
- adds underline and pointer finger cursor on link hover
> Updates link styles for posts

- app/models/user.rb
> Updates user model

- app/views/tags/show.html.slim
> Only show dashboard link if user logged in

- app/assets/stylesheets/core/_type.scss
> Revert link text-decoration hover style to none

- app/models/user.rb
> Fix username validation to not allow special characters

- app/assets/stylesheets/core/_flash.scss
- app/controllers/posts_controller.rb
- app/views/shared/_flash_notices.html.slim
> Redirect logged out users to root and show notice

- app/javascript/components/PostEditor.js
- app/javascript/components/editor-config/images.js
- app/javascript/components/editor-config/index.js
- app/javascript/components/editor-config/keys.js
- app/javascript/components/editor-config/marks.js
- app/javascript/components/editor-config/menu.js
- app/javascript/components/editor-config/rules.js
- app/javascript/components/editor-config/schema.js
- app/javascript/components/editor-config/title-menu.js
> Updates title marks menu 

- app/views/admin/posts/index.html.slim
> adds user column to admin posts index

- app/controllers/posts_controller.rb
- app/javascript/components/Editor.js
- app/javascript/components/PostEditor.js
- app/javascript/components/editor-config/index.js
- app/javascript/components/editor-config/plugin-comment.js
> Adds real-time comment rendering JEL-78

- app/controllers/posts_controller.rb
- app/javascript/components/Editor.js
- app/javascript/components/editor-config/index.js
- app/javascript/components/editor-config/plugin-comment.js
> Revert "Adds real-time comment rendering JEL-78"

- app/assets/stylesheets/editor.scss
- app/assets/stylesheets/posts.scss
https://www.loom.com/share/95f2ac0e85be43c29afab1e2b7bfe255
> Fixes editor reading experience on mobile

- app/javascript/components/editor-config/marks.js
https://www.loom.com/share/c0b2058653714ac89b5559df90e8a034?focus_title=1&muted=1
> Updates editor to generate links to open in new browser tab

- app/assets/stylesheets/posts.scss
- app/javascript/components/editor-config/plugin-comment.js
> Fixes image styles

- app/controllers/posts_controller.rb
- app/javascript/components/Editor.js
- app/javascript/components/editor-config/index.js
- app/javascript/components/editor-config/plugin-comment.js
This PR brings back real-time comment rendering.
> RT editor comments

- Contributing.md
> Updates contributing readme

- Gemfile.lock
- app/assets/stylesheets/comments.scss
- app/assets/stylesheets/core/_navs.scss
- app/assets/stylesheets/core/_type.scss
- app/assets/stylesheets/editor.scss
- app/assets/stylesheets/editor/defaults.scss
- app/assets/stylesheets/editor/masthead.scss
- app/assets/stylesheets/editor/menubar.css
- app/assets/stylesheets/editor/sidebar.scss
- app/assets/stylesheets/posts.scss
- app/javascript/components/Citations.js
- app/javascript/components/Floater.js
- app/javascript/components/PostEditor.js
- app/javascript/components/PostMasthead.js
- app/javascript/components/Sidebar.js
- app/javascript/components/editor-config/comments.js
- app/javascript/components/editor-config/keys.js
- app/models/post.rb
- app/serializers/citation_serializer.rb
- app/serializers/post_serializer.rb
- app/services/grobid_service.rb
- app/views/posts/_placeholder_post.html.slim
- app/views/posts/show.html.slim
- app/workers/broadcast_posts_channel_worker.rb
This PR adds a new component for a toggleable sidebar minimap for posts. It also changes the post page editor layout to use bootstrap columns that collapse, and changes the styling of annotations to use the gutter.
> Adds post component Sidebar minimap

- package.json
- yarn.lock
Adds lodash to package.json for versioning.
> Adds lodash as dependency

- app/assets/stylesheets/posts.scss
- app/javascript/components/Backlinks.js
- app/javascript/components/PostEditor.js
- app/javascript/components/Sidebar.js
- app/models/citation.rb
- app/models/post.rb
- app/serializers/backlink_serializer.rb
- app/serializers/post_serializer.rb
- app/serializers/user_serializer.rb
- app/views/posts/_backlinks.html.slim
- app/views/posts/_citations.html.slim
- app/views/posts/_placeholder_post.html.slim
- app/views/posts/show.html.slim
This PR adds a new feature which shows bidirectional reference links between posts.
> Adds citation linking to posts

- app/assets/stylesheets/editor/masthead.scss
- app/javascript/components/PostEditor.js
> Restores upload button to post masthead

- app/assets/stylesheets/editor.scss
- app/javascript/components/PostEditor.js
- app/javascript/components/PostLinkSearch.js
- app/javascript/components/editor-config/links.js
- app/javascript/components/editor-config/plugins.js
1. fixes eslint warning for missing onkeypress handler
2. fixes eslint warning for missing tabindex
3. fixes styling for form
> Fix eslint warnings

- app/controllers/tags_controller.rb
- app/views/tags/new.html.slim
> assigns user_id when creating new tag 

- app/assets/stylesheets/editor/masthead.scss
Todo: need to refactor the editors styles.
> Fix title comment css centering

- app/assets/stylesheets/postlinks.scss
- app/javascript/components/PostLinkSearch.js
https://www.loom.com/share/a1ec733c31e94e95a3c755369d22fdaa
This PR has to go in first before https://github.com/jellypbc/poster/pull/285.
> Refactors PostLinkSearch.js as function component

- app/assets/stylesheets/editor/defaults.scss
- app/assets/stylesheets/editor/masthead.scss
- app/assets/stylesheets/posts.scss
- app/javascript/components/PostEditor.js
https://www.loom.com/share/fa61076a470a4249bf5b703f4503de43
> Updates post styles for xs screen size

- app/javascript/components/editor-config/citations.js
Citation title is set successfully.
> Sets citation title in submitCitationCreate

- app/assets/stylesheets/editor/sidebar.scss
- app/javascript/components/Sidebar.js
fixes https://github.com/jellypbc/poster/issues/284
https://www.loom.com/share/8d85f884fa9b4dbb8850e3ebbc13f92f
> Disables sidebar links and updates toggle animation

- app/assets/stylesheets/posts.scss
- app/assets/stylesheets/users.scss
- app/controllers/tags_controller.rb
- app/helpers/posts_helper.rb
- app/views/pages/dashboard.html.slim
- app/views/posts/_form.html.slim
- app/views/posts/_post.html.slim
- app/views/tags/show.html.slim
https://www.loom.com/share/b00d8a212b174d0e8e9e09fcc655378f
new: 
old:
> Tag and collection polish 

- app/javascript/components/CitationSearch.js
- app/javascript/components/CommentForm.js
- app/javascript/components/ImageModal.js
- app/javascript/components/PostEditor.js
- app/javascript/components/PostPage.js
- app/javascript/components/editor-config/citations.js
- app/javascript/components/editor-config/comments.js
- app/javascript/components/editor-config/images.js
- app/javascript/reducers/imagesReducer.js
- app/javascript/store.js
- package.json
- yarn.lock
> Relocates store.js

- app/assets/stylesheets/posts.scss
- app/views/posts/edit.html.slim
> Fixes post edit page styles

- config/environments/production.rb
Fixes #319
Forces https:// for all connections to app in production.
> Forces all access to app over SSL

- app/controllers/posts_controller.rb
- app/javascript/components/PostEditor.js
Temporarily disable reloading new post on save, until we fix this with rt-collab.
> Turn off actionable editor reloading

- config/environments/production.rb
> Fix typo in production.rb

- config/initializers/shrine.rb
> Fix shrine config typo

- config/initializers/shrine.rb
> Fix typo in shrine config

- app/mailers/user_mailer.rb
> Fix user mailer welcome

- app/assets/stylesheets/core/_buttons.scss
- app/assets/stylesheets/core/_layout.scss
- app/assets/stylesheets/core/_pagination.scss
- app/assets/stylesheets/core/_type.scss
- app/assets/stylesheets/core/variables.scss
- app/assets/stylesheets/devise.scss
- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/posts.scss
- app/assets/stylesheets/uploads.scss
- app/assets/stylesheets/users.scss
- app/controllers/sessions_controller.rb
- app/views/layouts/application.html.slim
- app/views/pages/index.html.slim
- app/views/shared/_footer.html.slim
This PR replaces use of $brandGreen with $brandLink for all links, and fixes up the footer layout.
> Misc layout and style fixes

- app/controllers/concerns/no_index.rb
- app/controllers/posts_controller.rb
- app/controllers/users_controller.rb
Adds no_index concern for posts and users for now.
> Adds noindex response headers for posts and users

- Gemfile
- Gemfile.lock
- spec/requests/comments_request_spec.rb
Restores the skipped request specs for comments.
> Bump rails-controller-testing to fix request specs

- Gemfile
- Gemfile.lock
> Adds New Relic gem in production

- .env.development
- app/controllers/posts_controller.rb
- app/javascript/components/Sidebar.tsx
- app/models/upload.rb
- app/models/user.rb
- app/views/posts/_placeholder_post.html.slim
- config/environments/development.rb
- docker-compose.yml
This PR also temporarily stops showing the post body in the `placeholder_post` for when `<table>` breaks it.
> Fixes upload url in localhost for use with docker

- app/serializers/user_serializer.rb
> Remove unused posts attribute in user serializer

- app/javascript/components/PostEditor.tsx
- app/views/posts/show.html.slim
Typescript wasn't catching or casting that the editable prop was null.
> Fixes editable prop in post editor

- app/controllers/comments_controller.rb
- app/javascript/components/editor-config/comments.js
This PR stores highlightedText data in the highlighted_text column of the comment model when a new comment is created.
> Stores highlightedText data when a new comment is created
